server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joseacarmo17/BootcampNttData.git
        default-label: master
        search-paths:
        - '*service*'

